<?php

/**
 * Copyright © Klevu Oy. All rights reserved. See LICENSE.txt for license details.
 */

declare(strict_types=1);

use Klevu\Analytics\ViewModel\Escaper as EscaperViewModel;
use Klevu\Configuration\Block\Adminhtml\Backend\Template;

/**
 * @var Template $block
 * @var EscaperViewModel $escaperViewModel
 */
$escaperViewModel = $block->getData('escaper_view_model');
$escaper = $escaperViewModel->getEscaper();
?>
<section class="admin__page-section">
    <div class="admin__page-section-title"></div>

    <div class="admin__page-section-content" style="display: flex; gap: 20px; margin-left: -10px; margin-right: -10px;">
        <section style="flex-basis: 50%;">
            <h2><?= $escaper->escapeHtml(__('Configuration')->render()) ?></h2>
            <p>
                <?= $escaper->escapeHtml(
                    data: __(
                        'You can find settings to update sync configuration, including status and automated '
                        . 'schedule, under %1Klevu%2 &gt; %1Data Sync%2 &gt; %1Order Analytics%2.',
                        '<strong>',
                        '</strong>',
                    )->render(),
                    allowedTags: ['strong'],
                ) ?>
            </p>

            <p>
                <?= $escaper->escapeHtml(
                    data: __(
                        'Advanced configuration options can be found under '
                        . '%1Klevu%2 &gt; %1Developer Settings%2 &gt; %1Order Analytics%2.',
                        '<strong>',
                        '</strong>',
                    )->render(),
                    allowedTags: ['strong'],
                ) ?>
            </p>
        </section>

        <section style="flex-basis: 50%;">
            <h2><?= $escaper->escapeHtml(__('Useful Links')->render()) ?></h2>
            <p>
                <?= $escaper->escapeHtml(
                    data: __(
                        'Our %1Documentation%2 contains in-depth guides and articles on Klevu Analytics. '
                        . 'Some pertinent ones can be found below:',
                        '<a href="https://docs.klevu.com/klevu-magento-v4/analytics-overview" target="_blank">',
                        '</a>',
                    )->render(),
                    allowedTags: ['a'],
                ) ?>
            </p>
            <ul style="margin-left: 20px;">
                <li>
                    <a href="https://docs.klevu.com/klevu-magento-v4/analytics-user-interface"
                       target="_blank"><?= $escaper->escapeHtml(
                           __('Analytics User Interface')->render(),
                        ) ?></a>
                </li>
                <li>
                    <a href="https://docs.klevu.com/klevu-magento-v4/analytics-order-sync-history"
                       target="_blank"><?= $escaper->escapeHtml(
                           __('Order Sync History')->render(),
                        ) ?></a>
                </li>
                <li>
                    <a href="https://docs.klevu.com/klevu-magento-v4/analytics-faqs-and-troubleshooting"
                       target="_blank"><?= $escaper->escapeHtml(
                           __('FAQs and troubleshooting')->render(),
                        ) ?></a>
                </li>
            </ul>
        </section>
    </div>
</section>
